services:
  - type: web
    name: agentic-ai-rag-api
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT

    plan: free

    envVars:
      - key: GOOGLE_API_KEY
        sync: false

      - key: PINECONE_API_KEY
        sync: false

      - key: PINECONE_INDEX_NAME
        value: agentic-ai-rag

      - key: CHAT_MODEL
        value: gemini-flash-latest

      - key: EMBEDDING_MODEL
        value: gemini-embedding-2-preview

      - key: TOP_K
        value: "4"